// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProductsRequestParams creates a new ProductsRequestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProductsRequestParams() *ProductsRequestParams {
	return &ProductsRequestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProductsRequestParamsWithTimeout creates a new ProductsRequestParams object
// with the ability to set a timeout on a request.
func NewProductsRequestParamsWithTimeout(timeout time.Duration) *ProductsRequestParams {
	return &ProductsRequestParams{
		timeout: timeout,
	}
}

// NewProductsRequestParamsWithContext creates a new ProductsRequestParams object
// with the ability to set a context for a request.
func NewProductsRequestParamsWithContext(ctx context.Context) *ProductsRequestParams {
	return &ProductsRequestParams{
		Context: ctx,
	}
}

// NewProductsRequestParamsWithHTTPClient creates a new ProductsRequestParams object
// with the ability to set a custom HTTPClient for a request.
func NewProductsRequestParamsWithHTTPClient(client *http.Client) *ProductsRequestParams {
	return &ProductsRequestParams{
		HTTPClient: client,
	}
}

/* ProductsRequestParams contains all the parameters to send to the API endpoint
   for the products request operation.

   Typically these are written to a http.Request.
*/
type ProductsRequestParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the products request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductsRequestParams) WithDefaults() *ProductsRequestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the products request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductsRequestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the products request params
func (o *ProductsRequestParams) WithTimeout(timeout time.Duration) *ProductsRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the products request params
func (o *ProductsRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the products request params
func (o *ProductsRequestParams) WithContext(ctx context.Context) *ProductsRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the products request params
func (o *ProductsRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the products request params
func (o *ProductsRequestParams) WithHTTPClient(client *http.Client) *ProductsRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the products request params
func (o *ProductsRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ProductsRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
